from __future__ import annotations

import argparse
import json
from pathlib import Path


PROJECT_DIR = Path(__file__).resolve().parents[2]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Merge Linux and Windows Phase 4L release acceptance reports."
    )
    parser.add_argument(
        "--phase4k-report",
        type=Path,
        default=PROJECT_DIR / "docs/phase4k_reproducible_release_acceptance.json",
    )
    parser.add_argument(
        "--linux-report",
        type=Path,
        default=PROJECT_DIR / "docs/linux_phase4l_release_validation.json",
    )
    parser.add_argument(
        "--linux-package-packing0",
        type=Path,
        default=PROJECT_DIR / "docs/linux_phase4l_package_rehearsal_packing0.json",
    )
    parser.add_argument(
        "--linux-package-packing1",
        type=Path,
        default=PROJECT_DIR / "docs/linux_phase4l_package_rehearsal_packing1.json",
    )
    parser.add_argument(
        "--windows-report",
        type=Path,
        default=PROJECT_DIR / "docs/windows_phase4l_reproduced_artifact_acceptance.json",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=PROJECT_DIR / "docs/phase4l_dual_platform_release_acceptance.json",
    )
    parser.add_argument(
        "--milestone",
        type=Path,
        default=PROJECT_DIR / "docs/phase4l_dual_platform_release_acceptance_milestone.md",
    )
    return parser.parse_args()


def load(path: Path) -> dict[str, object]:
    if not path.is_file():
        raise RuntimeError(f"Missing report: {path}")
    return json.loads(path.read_text(encoding="utf-8"))


def require_passed(name: str, report: dict[str, object]) -> None:
    if report.get("status") != "passed":
        raise RuntimeError(f"{name} did not pass: {report.get('status')}")


def as_list(value: object) -> list[object]:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    return [value]


def write_json(path: Path, report: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(report, indent=2, ensure_ascii=True) + "\n",
        encoding="utf-8",
    )


def write_milestone(path: Path, report: dict[str, object]) -> None:
    phase4k = report["phase4k_reproduction"]
    linux = report["linux_release_acceptance"]
    windows = report["windows_reproduced_artifact_acceptance"]
    lines = [
        "# Phase 4L Dual-Platform Reproduced Release Acceptance",
        "",
        "## Status",
        "",
        "Phase 4L is complete.",
        "",
        "The runtime artifacts regenerated by Phase 4K were used as the release",
        "model source for Linux package validation and native Windows/MSVC",
        "validation. Both platforms confirmed offline install and OCR execution.",
        "",
        "## Inputs",
        "",
        f"- Phase 4K report: `{phase4k['report']}`",
        f"- Phase 4K staging model: `{phase4k['staging_model_dir']}`",
        f"- Staging manifest SHA-256: `{phase4k['runtime_manifest_sha256']}`",
        f"- Staging compatibility SHA-256: `{phase4k['runtime_compatibility_sha256']}`",
        "",
        "## Linux Acceptance",
        "",
        f"- Report: `{linux['report']}`",
        f"- Model directory: `{linux['model_directory']}`",
        f"- CTest suites passed: {', '.join(linux['ctest_suites'])}",
        f"- Packages produced: {len(linux['packages'])}",
        "- Package rehearsal packed mode: passed",
        "- Package rehearsal unpacked mode: passed",
        "",
        "## Windows Acceptance",
        "",
        f"- Report: `{windows['report']}`",
        f"- NTFS model directory: `{windows['ntfs_model_directory']}`",
        f"- Manifest-selected copied files: {windows['model_copy_file_count']}",
        f"- Windows CTest suites passed: {', '.join(windows['ctest_suites'])}",
        f"- Windows packages produced: {len(windows['packages'])}",
        "- Windows package rehearsal packed mode: passed",
        "- Windows package rehearsal unpacked mode: passed",
        "",
        "## Conclusion",
        "",
        "The Phase 4K reproduced runtime artifacts can be used as release inputs",
        "for both Linux and native Windows. The Linux installed package and the",
        "Windows ZIP package were both extracted into clean directories and ran",
        "OCR successfully in packed and unpacked modes without network access.",
        "",
        "## Remaining Risks",
        "",
        "- Full dual-platform validation remains large and slow, so it should stay",
        "  as an explicit release gate rather than a default developer test.",
        "- Windows artifacts are consumed from a manifest-selected NTFS copy of the",
        "  Linux-generated staging directory; rerun the copy step after any model",
        "  regeneration.",
        "- Before public release, run the same gate once more from the final clean",
        "  release commit and archive the produced packages externally.",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    phase4k = load(args.phase4k_report)
    linux = load(args.linux_report)
    linux_pack0 = load(args.linux_package_packing0)
    linux_pack1 = load(args.linux_package_packing1)
    windows = load(args.windows_report)

    for name, report in (
        ("Phase 4K", phase4k),
        ("Linux release", linux),
        ("Linux package packing0", linux_pack0),
        ("Linux package packing1", linux_pack1),
        ("Windows release", windows),
    ):
        require_passed(name, report)

    windows_ctest = as_list(windows.get("ctest", []))
    windows_packages = as_list(windows.get("packages", []))
    windows_package_rehearsals = as_list(windows.get("package_rehearsals", []))
    linux_ctest = linux.get("ctest", {})
    merged = {
        "phase": "4L",
        "status": "passed",
        "phase4k_reproduction": {
            "report": str(args.phase4k_report),
            "staging_model_dir": phase4k["work_dir"] + "/direct-staging-artifacts",
            "elapsed_seconds": phase4k["elapsed_seconds"],
            "runtime_manifest_sha256": phase4k["key_sha256"][
                "staging_runtime_manifest"
            ]["sha256"],
            "runtime_compatibility_sha256": phase4k["key_sha256"][
                "staging_runtime_compatibility"
            ]["sha256"],
            "manifest_file_count": phase4k["manifest"]["file_count"],
            "manifest_total_gib": phase4k["manifest"]["total_gib"],
            "existing_artifacts_reference_unchanged": phase4k[
                "existing_artifacts_reference_unchanged"
            ],
        },
        "linux_release_acceptance": {
            "report": str(args.linux_report),
            "status": linux["status"],
            "model_directory": linux["model_directory"],
            "ctest_suites": sorted(linux_ctest.keys()),
            "ctest": linux_ctest,
            "packages": linux["packages"],
            "package_rehearsals": [linux_pack0, linux_pack1],
        },
        "windows_reproduced_artifact_acceptance": {
            "report": str(args.windows_report),
            "status": windows["status"],
            "source_model_directory": windows["source_model_directory"],
            "ntfs_model_directory": windows["ntfs_model_directory"],
            "model_copy_file_count": windows["model_copy"]["file_count"],
            "model_copy_total_bytes": windows["model_copy"]["total_bytes"],
            "model_manifest_sha256": windows["model_manifest_sha256"],
            "model_compatibility_sha256": windows["model_compatibility_sha256"],
            "ctest_suites": [entry["suite"] for entry in windows_ctest],
            "ctest": windows_ctest,
            "packages": windows_packages,
            "package_rehearsals": windows_package_rehearsals,
        },
        "offline_release_acceptance": {
            "linux_installed_package_packed": True,
            "linux_installed_package_unpacked": True,
            "windows_installed_package_packed": True,
            "windows_installed_package_unpacked": True,
            "network_required": False,
        },
    }
    write_json(args.output, merged)
    write_milestone(args.milestone, merged)
    print(args.output)
    print(args.milestone)


if __name__ == "__main__":
    main()
